create table if not exists users
(
    id    bigint generated by default as identity
        constraint pk_user
            primary key,
    name  varchar(255) not null,
    status_user varchar,
    email varchar(512) not null
        constraint uq_user_email
            unique
);

create table if not exists category_events
(
    id            bigint generated by default as identity
        constraint category_events_pk
            primary key,
    name_category varchar
);

create table if not exists location
(
    location_id bigint generated by default as identity
        constraint location_pk
            primary key,
    lat         double precision,
    lon         double precision
);


create table if not exists events
(
    id      bigint generated by default as identity (maxvalue 2147483647)
        constraint events_pk
            primary key,
    annotation         varchar,
    category           bigint
        constraint events_category_events_id_fk
            references category_events on DELETE cascade,
    confirmed_requests bigint,
    created_on         timestamp default now(),
    description        varchar,
    event_date         timestamp default now(),
    initiator_id       bigint
        constraint events_users_id_fk
            references users on DELETE cascade,
    location_id        bigint
        constraint events_location_location_id_fk
            references location on DELETE cascade ,
    paid               boolean   default false,
    participant_limit  bigint,
    published_on       timestamp default now(),
    request_moderation boolean   default false,
    state              varchar,
    title              varchar,
    views              bigint
);



create table if not exists compilations
(
    compilation_id bigint
        constraint compilations_pk
            primary key generated by default as identity,
    title          varchar,
    pinned         boolean default false
);

create table if not exists compilations_events
(
    compilations_id bigint references compilations(compilation_id),
    event_id        bigint references events(id)
);

create table if not exists participations
(
    participation_id bigint generated by default as identity
        constraint participations_pk
            primary key,
    created          timestamp,
    event_id         bigint references events(id),
    requester_id     bigint references  users(id),
    status           varchar
);



