create table if not exists log_request_events
(
    id        bigint generated by default as identity
        constraint log_request_events_pk
            primary key,
    app       varchar,
    uri       varchar,
    ip        varchar,
    time timestamp
);

